Added new Uplift gym images
cuappdev/assets pull request #7
Opened 2019-10-17 03:07 UTC by CameronHamidi

Replaced the Uplift gym images with new ones from Design. Since the urls associated with Teagle Up and Teagle Down are currently separate, even though we now want them those gyms to show the same image, for now I replaced with the images for those two gyms with the same image. Once those changes get implemented in the backend, both gyms should display the "Teagle" image.

2019-10-17 20:59 UTC, ywsang approved these changes

2019-10-17 21:44 UTC, kevinchan159 requested changes
we should start to standardize how we name images. I think we should make them lowercased and separated by dashes, i.e.: `teagle-down` instead of `Teagle_Down`

2019-10-22 15:21 UTC, chalo2000 requested changes
What is the difference between Teagle, Teagle_Down, and Teagle_Up? The pictures are all the same.

2019-10-28 06:19 UTC, kevinchan159 approved these changes
lgtm!

2019-10-29 03:52 UTC, merged